version: "3.8"

volumes:
  db-data:

services:
  # MySQL
  db:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: $TZ
    volumes:
      - db-data:/var/lib/mysql
      - db-data:/etc/mysql/conf.d/my.cnf
    ports:
      - $DB_PORT:3306

  #【backend】Express
  app:
    build:
      context: .
    environment:
      TZ: $TZ
      DEBUG: $BACKEND_DEBUG
      DATABASE_URL: $BACKEND_DATABASE_URL
    tty: true
    ports:
      - $BACKEND_PORT:18080
    restart: always
    command: [sh, -c, npm install && npm run build && npm run start]
