version: "3.7"
services:
  app:
    image: node:16.14.0
    working_dir: /usr/src/app
    tty: true
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    command: >
      bash -c "npm install &&
      npm install nodemon -g &&
      nodemon src/index.ts"

  # DBサーバ
  db:
    # コンテナ名
    container_name: db
    # build
    image: mysql
    # 環境設定
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample1
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    # コンテナの中に入る
    tty: true
    # ボリューム
    volumes:
      - mysql_data:/var/lib/mysql
    # ポート開放
    ports:
      - 3306:3306

# 名前付きボリュームをdockerホストの管理下で作成
volumes:
  #
  mysql_data: {}
